### ISSUE TITLE
Plan for extension's release

### ISSUE THREAD

**Issue by Deadlyelder** [adem-wg/adem-chrome#1]
Are you considering making the extension release accessible here on Github? The link provided in the README currently directs to the GitLab instance, which requires access

**Comment by felixlinker** [comment]
Hi! Thanks for your interest in the project and catching that issue :) I updated the releases, the link to the releases, and also the published version.

Since the last time I updated the README, I also published the extension on the regular Chrome Webstore: https://chrome.google.com/webstore/detail/adem-dns-checker/ikjidcfbmgnajlnngicipbbekcdflcoi

I'd suggest, you install the extension from there!
